/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#663500",
        "on-tertiary-fixed-variant": "#900a18",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#6e3900",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#d23f40",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#004880",
        "surface-variant": "#e1e3e4",
        "primary-container": "#1777c9",
        "on-secondary-fixed": "#2f1500",
        "surface-tint": "#0060a8",
        "on-background": "#191c1d",
        "outline-variant": "#c0c7d3",
        "primary-fixed-dim": "#a1c9ff",
        "primary-fixed": "#d2e4ff",
        "secondary": "#904d00",
        "on-primary-container": "#fdfcff",
        "outline": "#717783",
        "on-secondary": "#ffffff",
        "tertiary": "#af262a",
        "inverse-on-surface": "#f0f1f2",
        "background": "#f8f9fa",
        "tertiary-fixed": "#ffdad7",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-surface": "#191c1d",
        "primary": "#005ea4",
        "surface-container": "#edeeef",
        "surface-dim": "#d9dadb",
        "secondary-container": "#fe932c",
        "on-tertiary-fixed": "#410004",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-primary-fixed": "#001c38",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9fa",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed-dim": "#ffb77d",
        "inverse-primary": "#a1c9ff",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#ffdcc3",
        "on-surface-variant": "#414751",
        "pothole-red": "#e57373",
        "normal-green": "#10b981",
      },
      fontFamily: {
        Inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "lg": "1.0rem",
        "xl": "1.25rem",
      },
      height: {
        "hero": "870px",
      }
    },
  },
  plugins: [],
}
