services:
  - type: web
    name: road-pothole-api
    runtime: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MODEL_PATH
        value: models/best_model_dual_v6_deeper_tf
      - key: ALLOWED_ORIGINS
        value: "*"
